services:
  # migration
  migrator:
    build:
      context: .
      target: app
    restart: "no"
    working_dir: /var/www
    volumes:
      - ./.env:/var/www/.env
    command: php artisan migrate --force
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_network

  # PHP-FPM Service
  app:
    build:
      context: .
      target: app
    container_name: netguard_alpha
    restart: always
    working_dir: /var/www
    volumes:
      - ./.env:/var/www/.env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    networks:
      - laravel_network

  # The Web Server Service
  webserver:
    build:
      context: .
      target: web
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_healthy
    networks:
      - laravel_network

  # The Database Service
  db:
    image: mysql:8.0
    container_name: netguard_alpha_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - laravel_network

# Define the network so they can talk
networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local