name: Netguard-Alpha CI

on:
  push:
    branches: [ "main" ]
jobs:
  laravel-docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env
        run: | 
          cp .env.example .env

          echo "${{ secrets.CI_TEST_ENV }}" > .env

      - name: Build and Orchestrate
        run: docker compose -f docker-compose.yml up -d --build
      
      - name: Debug DB Failure
        if: failure() # Only runs if a previous step failed
        run: |
          docker compose logs db
          docker compose logs migrator
          docker inspect netguard_alpha_db --format='{{json .State.Health}}'
          docker inspect migration --format='{{json .State.Health}}'

      - name: Verify Container Health
        run: docker compose ps

      - name: Run Artisan Check
        run: docker compose exec -T app php artisan --version

      - name: Shutdown
        run: docker compose down -v