name: Netguard-Alpha CI

on:
  push:
    branches: [ "main" ]
jobs:
  laravel-docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env
        run: | 
          cp .env.example .env

          echo "DB_DATABASE=${{ env.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ env.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env
          echo "DB_ROOT_PASSWORD=${{ env.DB_ROOT_PASSWORD }}" >> .env

          php artisan key:generate --force

        env:
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

      - name: Build and Orchestrate
        run: docker compose -f docker-compose.yml up -d --build

      - name: Verify Container Health
        run: docker compose ps

      - name: Run Artisan Check
        run: docker compose exec -T app php artisan --version

      - name: Shutdown
        run: docker compose down -v